# Reference: https://docs.codecov.com/docs/codecov-yaml
#
# When modifying this file, please validate using:
#   curl -X POST --data-binary @.github/codecov.yml https://codecov.io/validate

codecov:
  require_ci_to_pass: false

coverage:
  range: "40...80"
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

parsers:
  go:
    partials_as_hits: true

ignore:
  - "tests"
