run:
  concurrency: 4
  timeout: 5m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - gci
    - gochecknoinits
#    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
#    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
#    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/hypnoglow/helm-s3)
  goimports:
    local-prefixes: github.com/hypnoglow/helm-s3

issues:
  exclude-rules:
    - linters:
        - golint
        - stylecheck
        - revive
      text: "error strings should not be capitalized"
    - linters:
        - staticcheck
      text: "strings.Title has been deprecated"
    # TODO: fix this later.
    - linters:
        - revive
      text: "^unused-parameter"
