version: "3"

vars: { }

env:
  GOBIN: "{{ .ROOT_DIR }}/bin"
  CGO_ENABLED: "0"
  PLUGIN_VERSION:
    sh: cat plugin.yaml | grep "version" | cut -d '"' -f 2

tasks:
  mod:
    desc: "Install dependencies"
    run: once
    cmds:
      - go mod tidy
  test-unit:
    desc: "Run unit tests"
    deps:
      - mod
    cmds:
      - go test $(go list ./... | grep -v e2e)
  lint:
    desc: "Run linter"
    deps:
      - mod
    cmds:
      - golangci-lint run {{ .CLI_ARGS }}
  build:
    desc: "Build plugin binary"
    run: once
    deps:
      - mod
    env:
      PLUGIN_VERSION:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
    cmds:
      - go build
        -o bin/helm-s3
        -ldflags "-X 'main.version=${PLUGIN_VERSION} (development)'"
        ./cmd/helm-s3
  install:
    desc: "Install the plugin in development mode"
    deps:
      - build
    env:
      HELM_S3_PLUGIN_NO_INSTALL_HOOK: "1"
    cmds:
      - helm plugin install .
  test-e2e:
    desc: "Run end-to-end tests"
    deps:
      - build
    cmds:
      - ./hack/test-e2e-local.sh {{ .CLI_ARGS }}
